handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 10
    max-connections: 10
    threads:
      min-spare: 2
      max: 5
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 10
